import { generatePalette, type Palette, STEPS } from "./palette.ts";
import {
  DEFAULT_DENSITY,
  DENSITIES,
  type DensityName,
  DURATIONS,
  FLOATING_SHADOW,
  FONT_FAMILIES,
  FONT_WEIGHTS,
  RADII,
  TYPE_SCALE,
} from "./scale.ts";
import {
  ALIASES,
  COMPONENT_TOKENS,
  FIXED,
  SEMANTIC_TOKENS,
  THEMES,
  type ThemeName,
  type TokenRef,
} from "./themes.ts";

/**
 * Emits the token stylesheet: `--mf-` custom properties in four layers. Switching axes are
 * `data-theme` (`light`, `dark`, `system`) and `data-density` on the app root or any subtree.
 */

const px = (value: number): string => `${value}px`;

function block(selector: string, lines: readonly string[]): string {
  return `${selector} {\n${lines.map((line) => `  ${line}`).join("\n")}\n}\n`;
}

function refVar(tokenRef: TokenRef): string {
  if (typeof tokenRef === "string") return `var(--mf-${tokenRef})`;
  return `var(--mf-${tokenRef.alias}-${tokenRef.step})`;
}

/** The declarations that switch the page to one theme. */
export function themeDeclarations(theme: ThemeName): string[] {
  return [
    `color-scheme: ${theme};`,
    ...SEMANTIC_TOKENS.map((token) => `--mf-color-${token}: ${refVar(THEMES[theme][token])};`),
  ];
}

function densityLines(name: DensityName): string[] {
  const density = DENSITIES[name];
  return [
    `--mf-control-height: ${px(density.controlHeight)};`,
    `--mf-row-height: ${px(density.rowHeight)};`,
    `--mf-density-font-size: ${px(density.fontSize)};`,
    `--mf-density-line-height: ${px(density.lineHeight)};`,
    `--mf-padding-inline: ${px(density.paddingInline)};`,
    `--mf-padding-block: ${px(density.paddingBlock)};`,
    `--mf-gap: ${px(density.gap)};`,
  ];
}

export function generateTokenCss(palette: Palette = generatePalette()): string {
  const primitives = [
    ...Object.entries(FIXED).map(([name, hex]) => `--mf-${name}: ${hex};`),
    ...Object.entries(palette).flatMap(([ramp, steps]) =>
      STEPS.map((step) => `--mf-${ramp}-${step}: ${steps[step]};`),
    ),
  ];
  const aliases = Object.entries(ALIASES).flatMap(([alias, ramp]) =>
    STEPS.map((step) => `--mf-${alias}-${step}: var(--mf-${ramp}-${step});`),
  );
  const scale = [
    `--mf-font-sans: ${FONT_FAMILIES.sans};`,
    `--mf-font-mono: ${FONT_FAMILIES.mono};`,
    ...Object.entries(FONT_WEIGHTS).map(([name, weight]) => `--mf-font-weight-${name}: ${weight};`),
    ...Object.entries(TYPE_SCALE).flatMap(([name, { size, lineHeight }]) => [
      `--mf-font-size-${name}: ${px(size)};`,
      `--mf-line-height-${name}: ${px(lineHeight)};`,
    ]),
    ...Object.entries(RADII).map(([name, radius]) => `--mf-radius-${name}: ${px(radius)};`),
    ...Object.entries(DURATIONS).map(([name, ms]) => `--mf-duration-${name}: ${ms}ms;`),
    `--mf-shadow-floating: ${FLOATING_SHADOW};`,
  ];
  const components = Object.entries(COMPONENT_TOKENS).map(
    ([name, token]) => `--mf-${name}: var(--mf-color-${token});`,
  );
  const densities = (Object.keys(DENSITIES) as DensityName[]).filter(
    (name) => name !== DEFAULT_DENSITY,
  );

  return [
    "/* Generated by packages/ui/scripts/generate-tokens.ts from ADR-0024's anchors. Do not edit. */\n",
    "/* Primitive layer: the generated ramps. */",
    block(":root", primitives),
    "/* Alias layer: what each ramp is for. */",
    block(":root", aliases),
    "/* Type, shape, and motion. */",
    block(":root", scale),
    block("@media (prefers-reduced-motion: reduce)", [
      ":root {",
      "  --mf-duration-fast: 0ms;",
      "  --mf-duration-normal: 0ms;",
      "}",
    ]),
    '/* Semantic layer. Light is the default; data-theme="system" follows the OS. */',
    block(':root,\n[data-theme="light"],\n[data-theme="system"]', themeDeclarations("light")),
    block('[data-theme="dark"]', themeDeclarations("dark")),
    block("@media (prefers-color-scheme: dark)", [
      '[data-theme="system"] {',
      ...themeDeclarations("dark").map((line) => `  ${line}`),
      "}",
    ]),
    "/* Component layer: redeclared wherever a theme is set, so each subtree resolves its own. */",
    block(":root,\n[data-theme]", components),
    `/* Density. \`${DEFAULT_DENSITY}\` is the default. */`,
    block(`:root,\n[data-density="${DEFAULT_DENSITY}"]`, densityLines(DEFAULT_DENSITY)),
    ...densities.map((name) => block(`[data-density="${name}"]`, densityLines(name))),
  ].join("\n");
}

/**
 * Emits the Tailwind v4 theme (ADR-0023): Tailwind's own colours, fonts, sizes, radii, and
 * shadows are cleared, so screens can name only the semantic and component tokens —
 * `bg-surface`, `text-text-muted`, `border-field-border`, `h-control` — never a primitive.
 * `inline` keeps the `var(--mf-…)` references, so `data-theme` and `data-density` switch them.
 */
export function generateTailwindThemeCss(): string {
  const colors = [
    ...SEMANTIC_TOKENS.map((token) => `--color-${token}: var(--mf-color-${token});`),
    ...Object.keys(COMPONENT_TOKENS).map((name) => `--color-${name}: var(--mf-${name});`),
  ];
  const text = Object.keys(TYPE_SCALE).flatMap((step) => [
    `--text-${step}: var(--mf-font-size-${step});`,
    `--text-${step}--line-height: var(--mf-line-height-${step});`,
  ]);
  const lines = [
    "--color-*: initial;",
    "--color-transparent: transparent;",
    ...colors,
    "--font-*: initial;",
    "--font-sans: var(--mf-font-sans);",
    "--font-mono: var(--mf-font-mono);",
    "--text-*: initial;",
    ...text,
    "--text-density: var(--mf-density-font-size);",
    "--text-density--line-height: var(--mf-density-line-height);",
    ...Object.keys(FONT_WEIGHTS).map(
      (name) => `--font-weight-${name}: var(--mf-font-weight-${name});`,
    ),
    "--radius-*: initial;",
    ...Object.keys(RADII).map((name) => `--radius-${name}: var(--mf-radius-${name});`),
    "--shadow-*: initial;",
    "--shadow-floating: var(--mf-shadow-floating);",
    "--spacing-control: var(--mf-control-height);",
    "--spacing-row: var(--mf-row-height);",
    "--spacing-pad-inline: var(--mf-padding-inline);",
    "--spacing-pad-block: var(--mf-padding-block);",
    "--spacing-density-gap: var(--mf-gap);",
    "--default-transition-duration: var(--mf-duration-fast);",
  ];
  return (
    "/* Generated by packages/ui/scripts/generate-tokens.ts: the Tailwind v4 theme. Do not edit. */\n\n" +
    block("@theme inline", lines)
  );
}
